# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10

commands:
  restore_dependencies:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

            - v1-dependencies-
  save_dependencies:
    steps:
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  build:
    steps:
      - checkout
      - restore_dependencies
      - run: yarn install
      - save_dependencies

jobs:
  build_application:
    executor: node
    working_directory: ~/repo
    steps:
      - build

  test:
    executor: node
    working_directory: ~/repo
    steps:
      - build
      - run: yarn test

  deploy_hml:
    executor: node
    working_directory: ~/repo
    steps:
      - build
      # - severless-install

  deploy_prod:
    executor: node
    working_directory: ~/repo
    steps:
      - build
      # - severless-install

workflows:
  version: 2
  deploy:
    jobs:
      - build_application

      - test:
          requires:
            - build_application

      - hold_hml:
          type: approval
          requires:
            - test

      - deploy_hml:
          requires:
            - hold_hml

      - hold_prod:
          type: approval
          requires:
            - deploy_hml

      - deploy_prod:
          requires:
            - hold_prod
          filters:
            branches:
              only: master
